pipeline {
  agent any

  tools {
    maven 'maven-3'
  }

  environment {
    JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64'
    PATH = "${JAVA_HOME}/bin:${env.PATH}"

    APP_DIR   = "Gestion_Produit"
    IMAGE_TAG = "v1.${BUILD_NUMBER}"
    IMAGE     = "harbor.local:8081/staging/gestion:${IMAGE_TAG}"
  }

  stages {

    stage('Lint') {
      steps {
        dir("${APP_DIR}") {
          sh '''
            echo "verification regles de style"
            mvn checkstyle:check -Dcheckstyle.failOnViolation=false
          '''
        }
        sh '''
          echo "verification dockerfile"
          hadolint ${APP_DIR}/Dockerfile || true

          echo "verification yaml"
          yamllint . || true
        '''
      }
    }

    stage('Build') {
      steps {
        dir("${APP_DIR}") {
          sh '''
            echo "production de l'artefact (.jar)"
            mvn clean package -DskipTests
          '''
        }
      }
    }

    stage('Tests') {
      steps {
        dir("${APP_DIR}") {
          sh 'mvn test'
        }
      }
      post {
        always {
          junit testResults: "${APP_DIR}/target/surefire-reports/*.xml",
                allowEmptyResults: true
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        dir("${APP_DIR}") {
          withSonarQubeEnv('sonarqube') {
            sh '''
              mvn sonar:sonar \
                -Dsonar.projectKey=my-gestion-app \
                -Dsonar.projectName=my-gestion-app \
                -Dsonar.java.binaries=target
            '''
          }
        }
      }
    }

    stage('Dependency Check (SCA)') {
      steps {
        dir("${APP_DIR}") {
          sh 'mvn verify'
        }
      }
      post {
        always {
          archiveArtifacts artifacts: 'Gestion_Produit/target/dependency-check-report.html'
        }
      }
    }

    stage('Build Image') {
      steps {
        dir("${APP_DIR}") {
          sh 'docker build -t $IMAGE .'
        }
      }
    }

    stage('Scan Image (Trivy)') {
      steps {
        sh '''
          trivy image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            $IMAGE
        '''
      }
    }

    stage('Generate SBOM (Syft)') {
      steps {
        sh 'syft $IMAGE -o json > sbom.json'
        archiveArtifacts artifacts: 'sbom.json'
      }
    }

    stage('Sign Image (Cosign)') {
      environment {
        COSIGN_PASSWORD = credentials('cosign_password')
      }
      steps {
        withCredentials([
          file(credentialsId: 'cosign-private-key', variable: 'COSIGN_KEY')
        ]) {
          sh 'cosign sign --key $COSIGN_KEY $IMAGE'
        }
      }
    }

    stage('Push Image to Harbor') {
      steps {
        sh 'docker push $IMAGE'
      }
    }
  }
}
