pipeline {
    agent {
        docker {
            image "${harbor_registry}/agent/maven-jenkins-agent:v2"
            args "-v /var/run/docker.sock:/var/run/docker.sock"
            reuseNode true
        }    
    }

    stages{
        stage('Test agent') {
            steps {
                sh '''

                echo "User:"
                whoami

                echo "Docker Info"
                docker info | head -20

                echo "Try pull"
                docker pull ${arbor_registry}/agent/maven-jenkins-agent:v2

                '''
            }
        }
    }
}